imports:
    - { resource: handlers.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    queries.locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        public: false

    UselessSoft\Queries\QueryBusInterface:
        alias: UselessSoft\QueriesBundle\DeferredQueryBus
    UselessSoft\Queries\QueryHandlerInterface:
        alias: UselessSoft\QueriesBundle\DeferredQueryBus
    UselessSoft\Queries\Doctrine\QueryHandlerInterface:
        alias: UselessSoft\QueriesBundle\DeferredQueryBus
    UselessSoft\QueriesBundle\DeferredQueryBus:
        arguments:
            $locator: '@queries.locator'
            $handlerNames: []

    UselessSoft\Queries\QueryableInterface:
        alias: UselessSoft\Queries\Doctrine\Queryable
    UselessSoft\Queries\Doctrine\QueryableInterface:
        alias: UselessSoft\Queries\Doctrine\Queryable
    UselessSoft\Queries\Doctrine\Queryable:
